# Generated by Django 4.1 on 2022-09-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoNewsModel',
            fields=[
                ('newsid', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('relatedids', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('newstype', models.CharField(blank=True, max_length=255)),
                ('descendants', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
